"""
backend/db/models.py

SQLAlchemy declarative models for Project-CHIMERA.
Defines schema for:
  - Incident: Security incidents, severity, risk score, confidence, blast radius.
  - Event: Raw security logs, telemetry, and incoming payloads.
  - Action: Containment actions, playbooks, and n8n execution results.
  - Report: Forensic reports generated by ReportingAgent.
  - DecisionEdge / DecisionProvenance: Multi-agent reasoning and decision provenance graph edges.
  - GraphEdge: Attack topology and honeypot redirect graph edges.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from sqlalchemy import (
    DateTime,
    Float,
    ForeignKey,
    Index,
    JSON,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


# Portable JSON type: uses JSONB on PostgreSQL, standard JSON elsewhere
JSON_TYPE = JSON().with_variant(JSONB, "postgresql")


class Base(DeclarativeBase):
    """SQLAlchemy Declarative Base for all CHIMERA models."""
    pass


class Incident(Base):
    """
    Tracks security incidents, risk scores, confidence, and blast radius.
    """
    __tablename__ = "incidents"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: f"INC-2026-{uuid.uuid4().hex[:4].upper()}",
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    source_ip: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)
    destination_ip: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    endpoint: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    severity: Mapped[str] = mapped_column(String(50), nullable=False, default="HIGH")
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="PENDING_APPROVAL", index=True)
    risk_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0, index=True)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    mitre_technique: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    cert_in_category: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    decoy_path: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    blast_radius: Mapped[Dict[str, Any]] = mapped_column(JSON_TYPE, nullable=False, default=dict)
    metadata_json: Mapped[Dict[str, Any]] = mapped_column("metadata", JSON_TYPE, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships
    events: Mapped[List[Event]] = relationship(
        "Event",
        back_populates="incident",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    actions: Mapped[List[Action]] = relationship(
        "Action",
        back_populates="incident",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    reports: Mapped[List[Report]] = relationship(
        "Report",
        back_populates="incident",
        cascade="all, delete-orphan",
        lazy="selectin",
    )
    decision_edges: Mapped[List[DecisionEdge]] = relationship(
        "DecisionEdge",
        back_populates="incident",
        cascade="all, delete-orphan",
        lazy="selectin",
    )

    def to_dict(self) -> Dict[str, Any]:
        """Convert model instance to a JSON-serializable dictionary for API/WebSocket."""
        created_str = (
            self.created_at.isoformat()
            if isinstance(self.created_at, datetime)
            else str(self.created_at or "")
        )
        updated_str = (
            self.updated_at.isoformat()
            if isinstance(self.updated_at, datetime)
            else str(self.updated_at or "")
        )
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description or "",
            "source_ip": self.source_ip or "127.0.0.1",
            "destination_ip": self.destination_ip or "",
            "endpoint": self.endpoint or "",
            "severity": self.severity,
            "cert_in_category": self.cert_in_category or "Unauthorized access to IT systems or data",
            "risk_score": round(float(self.risk_score or 0.0), 3),
            "confidence": round(float(self.confidence or 0.0), 2),
            "status": self.status,
            "mitre_technique": self.mitre_technique or "T1190 – Exploit Public-Facing Application",
            "decoy_path": self.decoy_path or "/decoy/db-admin",
            "blast_radius": self.blast_radius or {},
            "metadata": self.metadata_json or {},
            "created_at": created_str,
            "updated_at": updated_str,
        }


class Event(Base):
    """
    Stores raw telemetry, logs, and security events linked to incidents.
    """
    __tablename__ = "events"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    incident_id: Mapped[Optional[str]] = mapped_column(
        String(64),
        ForeignKey("incidents.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    event_type: Mapped[str] = mapped_column(String(100), nullable=False, default="http_log")
    source: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    severity: Mapped[str] = mapped_column(String(50), nullable=False, default="INFO")
    payload: Mapped[Dict[str, Any]] = mapped_column(JSON_TYPE, nullable=False, default=dict)
    raw_log: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    incident: Mapped[Optional[Incident]] = relationship("Incident", back_populates="events")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "event_type": self.event_type,
            "source": self.source,
            "severity": self.severity,
            "payload": self.payload or {},
            "raw_log": self.raw_log or "",
            "timestamp": self.timestamp.isoformat() if isinstance(self.timestamp, datetime) else str(self.timestamp),
            "created_at": self.created_at.isoformat() if isinstance(self.created_at, datetime) else str(self.created_at),
        }


class Action(Base):
    """
    Tracks remediation actions and n8n playbook executions.
    """
    __tablename__ = "actions"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    incident_id: Mapped[Optional[str]] = mapped_column(
        String(64),
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    playbook_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    action_type: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="PENDING", index=True)
    payload: Mapped[Dict[str, Any]] = mapped_column(JSON_TYPE, nullable=False, default=dict)
    result: Mapped[Dict[str, Any]] = mapped_column(JSON_TYPE, nullable=False, default=dict)
    executed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    incident: Mapped[Optional[Incident]] = relationship("Incident", back_populates="actions")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "playbook_name": self.playbook_name,
            "action_type": self.action_type,
            "status": self.status,
            "payload": self.payload or {},
            "result": self.result or {},
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class Report(Base):
    """
    Stores incident forensic reports generated by ReportingAgent.
    """
    __tablename__ = "reports"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    incident_id: Mapped[str] = mapped_column(
        String(64),
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    content: Mapped[Dict[str, Any]] = mapped_column(JSON_TYPE, nullable=False, default=dict)
    generated_by: Mapped[str] = mapped_column(String(100), nullable=False, default="ReportingAgent")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    incident: Mapped[Incident] = relationship("Incident", back_populates="reports")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "title": self.title,
            "summary": self.summary,
            "content": self.content or {},
            "generated_by": self.generated_by,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class DecisionEdge(Base):
    """
    Decision Provenance & Multi-Agent Reasoning Graph Edges.
    Maps relationships between agents, telemetry, findings, and remediation decisions.
    """
    __tablename__ = "decision_edges"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    incident_id: Mapped[Optional[str]] = mapped_column(
        String(64),
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    source_node: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    target_node: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    edge_type: Mapped[str] = mapped_column(String(100), nullable=False, default="decision_flow", index=True)
    agent_name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    metadata_json: Mapped[Dict[str, Any]] = mapped_column("metadata", JSON_TYPE, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    incident: Mapped[Optional[Incident]] = relationship("Incident", back_populates="decision_edges")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "source_node": self.source_node,
            "target_node": self.target_node,
            "edge_type": self.edge_type,
            "agent_name": self.agent_name,
            "reasoning": self.reasoning,
            "metadata": self.metadata_json or {},
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class GraphEdge(Base):
    """
    Attack topology and honeypot redirect graph edges for live deception mapping.
    """
    __tablename__ = "graph_edges"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    incident_id: Mapped[Optional[str]] = mapped_column(
        String(64),
        ForeignKey("incidents.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    source_node: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    target_node: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    edge_type: Mapped[str] = mapped_column(String(100), nullable=False, default="redirected_to")
    metadata_json: Mapped[Dict[str, Any]] = mapped_column("metadata", JSON_TYPE, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "incident_id": self.incident_id,
            "source_node": self.source_node,
            "target_node": self.target_node,
            "edge_type": self.edge_type,
            "metadata": self.metadata_json or {},
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
