"""
backend/agents/reporting_agent.py

ReportingAgent — generates a concise Markdown forensic report from all
gathered pipeline data using an LLM.

Input bundle (passed as keyword arguments or a dict):
    triage_json    : dict from TriageAgent.classify()
    intel_json     : dict from ThreatIntelAgent.enrich()
    risk_score     : float from RiskEngine.calculate_risk()
    risk_assessment: dict from RiskEngine.evaluate_action()
    graph_edges    : list[dict] — graph_edges records from DeceptionAgent
    incident_id    : str (optional — used in the report header)
    deception_path : str (optional — decoy path from DeceptionAgent)

Output:
    {
        "incident_id":  str,
        "summary_md":   str,   ← full Markdown forensic report
        "generated_at": str,   ← ISO-8601 UTC timestamp
        "model":        str,
    }
"""

from __future__ import annotations

import json
import logging
import os
import re
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
try:
    from groq import AsyncGroq
except ImportError:
    AsyncGroq = None

from backend.config import settings
from backend.fixtures.loader import is_demo_mode, get_demo_fixture, simulate_agent_latency

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# LLM configuration
# ---------------------------------------------------------------------------

_GROQ_MODEL = os.getenv("GROQ_MODEL", getattr(settings, "GROQ_MODEL", "llama-3.1-8b-instant"))

_SYSTEM_PROMPT = """\
You are CHIMERA Forensics — an elite SOC reporting analyst AI embedded in
an autonomous Security Operations Centre.

You will be given a structured JSON bundle containing the full pipeline output
for a single security incident. Your task is to synthesise this data into a
concise, professional Markdown forensic report.

## Report Structure (use these exact headings):

# 🛡️ CHIMERA Incident Report — {INCIDENT_ID}

## Executive Summary
*2–3 sentence non-technical summary for leadership.*

## Threat Classification
| Field             | Value |
|-------------------|-------|
| Severity          | ...   |
| MITRE Tactic      | ...   |
| MITRE Technique   | ...   |
| Confidence Score  | ...   |
| Risk Score        | ...   |
| Risk Band         | ...   |

## Threat Intelligence
*Summarise the IOC reputation and Tavily web findings in 3–5 sentences.*

## Timeline & Attack Chain
*Bullet list of the key events/steps inferred from the data.*

## Deception Layer
*State which decoy endpoint the attacker was redirected to and why.*

## Recommended Actions
*Bullet list of concrete, prioritised remediation steps.*
Prefix critical items with ⚠️.

## Graph Topology
*Briefly describe the recorded graph edges (attacker → decoy).*

---
*Generated by CHIMERA AutoSOC at {TIMESTAMP} UTC*

Rules:
- Use only the data provided — do NOT invent facts.
- Keep the report under 600 words.
- All headings must use exactly the format shown.
- Use Markdown tables where structure helps readability.
- Highlight critical items with ⚠️ or **bold**.
- Respond with ONLY the Markdown report — no preamble, no JSON, no code fences.
"""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_bundle_summary(
    triage_json: dict[str, Any],
    intel_json: dict[str, Any],
    risk_score: float,
    risk_assessment: dict[str, Any],
    graph_edges: list[dict[str, Any]],
    incident_id: str,
    deception_path: str,
) -> str:
    """Serialise the full pipeline bundle into a compact prompt payload."""
    bundle = {
        "incident_id": incident_id,
        "triage": triage_json,
        "intel": intel_json,
        "risk_score": round(risk_score, 4),
        "risk_assessment": risk_assessment,
        "graph_edges": graph_edges,
        "deception_path": deception_path,
    }
    return json.dumps(bundle, indent=2, default=str)


def _inject_prompt_vars(system: str, incident_id: str) -> str:
    """Fill template variables in the system prompt."""
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    return (
        system
        .replace("{INCIDENT_ID}", incident_id)
        .replace("{TIMESTAMP}", now_utc)
    )


def _strip_fences(text: str) -> str:
    """Remove accidental markdown code fences the LLM may add."""
    text = re.sub(r"^```(?:markdown)?\s*\n?", "", text.strip(), flags=re.IGNORECASE)
    text = re.sub(r"\n?```\s*$", "", text.strip(), flags=re.IGNORECASE)
    return text.strip()


def _fallback_report(
    incident_id: str,
    triage_json: dict[str, Any],
    intel_json: dict[str, Any],
    risk_score: float,
    risk_assessment: dict[str, Any],
    deception_path: str,
) -> str:
    """Rule-based Markdown report used when the LLM is unavailable."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    severity   = triage_json.get("severity", "UNKNOWN")
    tactic     = triage_json.get("mitre_tactic", "Unknown")
    technique  = triage_json.get("mitre_technique", "Unknown")
    reasoning  = triage_json.get("reasoning", "")
    ioc        = intel_json.get("ioc", "N/A")
    confidence = intel_json.get("confidence_score", 0.0)
    context    = intel_json.get("threat_context", "")
    action     = risk_assessment.get("action", "unknown")
    risk_label = risk_assessment.get("risk_label", "UNKNOWN")
    requires_h = risk_assessment.get("requires_human", False)

    return f"""# 🛡️ CHIMERA Incident Report — {incident_id}

## Executive Summary
A **{severity}** severity event was detected and automatically triaged by the CHIMERA \
multi-agent pipeline. The attacker IOC `{ioc}` has a threat confidence of **{confidence:.0%}** \
and a composite risk score of **{risk_score:.4f}** ({risk_label}). \
{"⚠️ Human analyst review is required." if requires_h else "Automated containment has been initiated."}

## Threat Classification
| Field             | Value                  |
|-------------------|------------------------|
| Severity          | {severity}             |
| MITRE Tactic      | {tactic}               |
| MITRE Technique   | {technique}            |
| Confidence Score  | {confidence:.4f}       |
| Risk Score        | {risk_score:.4f}       |
| Risk Band         | {risk_label}           |

## Threat Intelligence
{context if context else "No threat context available."}

## Timeline & Attack Chain
- IOC `{ioc}` flagged by XGBoost EdgeFilter
- TriageAgent classified as **{severity}** — {reasoning}
- ThreatIntelAgent enrichment completed (confidence: {confidence:.2%})
- Risk score computed: {risk_score:.4f} → action: **{action}**
- Attacker redirected to decoy endpoint: `{deception_path}`

## Deception Layer
The attacker was redirected to `{deception_path}` based on the detected \
MITRE technique **{technique}**, directing activity away from production systems.

## Recommended Actions
{"⚠️ **Escalate to Tier-2 analyst immediately.**" if requires_h else "- ✅ Automated containment initiated."}
- Verify `{ioc}` is blocked at the perimeter firewall.
- Cross-reference with SIEM for historical activity from this IOC.
- Review graph topology for lateral movement indicators.

## Graph Topology
The graph edge `ip:{ioc}` → `decoy:{deception_path}` (type: `redirected_to`) \
has been recorded in the graph database.

---
*Generated by CHIMERA AutoSOC (fallback mode) at {now} UTC*
"""


# ---------------------------------------------------------------------------
# Public agent class
# ---------------------------------------------------------------------------

class ReportingAgent:
    """
    Generates a Markdown forensic report from the full CHIMERA pipeline output.
    In DEMO_MODE, returns deterministic comprehensive reports with simulated latency.
    """

    async def generate_report(
        self,
        incident_id: str,
        triage_json: dict[str, Any],
        intel_json: dict[str, Any],
        risk_score: float,
        risk_assessment: dict[str, Any],
        graph_edges: list[dict[str, Any]] | None = None,
        deception_path: str = "",
    ) -> dict[str, Any]:
        """
        Generate a Markdown forensic report using an LLM.
        """
        graph_edges = graph_edges or []
        generated_at = datetime.now(timezone.utc).isoformat()

        logger.info(
            "ReportingAgent.generate_report | incident_id=%s | risk=%.4f",
            incident_id,
            risk_score,
        )

        ioc = intel_json.get("ioc", "")

        # ── 1. DEMO_MODE Fast Deterministic Return ─────────────────────────
        if is_demo_mode():
            await simulate_agent_latency(250, 400)
            fixture = get_demo_fixture(ioc)
            if fixture and "report" in fixture and "summary_md" in fixture["report"]:
                summary_md = fixture["report"]["summary_md"].replace("{INCIDENT_ID}", incident_id)
                return {
                    "incident_id": incident_id,
                    "summary_md": summary_md,
                    "generated_at": generated_at,
                    "model": "demo-fixture-rehearsal",
                }

        # Build the user payload
        bundle_text = _build_bundle_summary(
            triage_json=triage_json,
            intel_json=intel_json,
            risk_score=risk_score,
            risk_assessment=risk_assessment,
            graph_edges=graph_edges,
            incident_id=incident_id,
            deception_path=deception_path,
        )

        # Inject template variables into system prompt
        system = _inject_prompt_vars(_SYSTEM_PROMPT, incident_id)

        try:
            if AsyncGroq is None:
                raise RuntimeError("Groq SDK is not installed in the environment.")
            groq_client = AsyncGroq(api_key=None)
            chat = await groq_client.chat.completions.create(
                model=_GROQ_MODEL,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user",   "content": bundle_text},
                ],
                temperature=0.3,
                max_tokens=1500,
            )
            raw_md = chat.choices[0].message.content or ""
            summary_md = _strip_fences(raw_md)
            model_used = _GROQ_MODEL

            logger.info(
                "ReportingAgent report generated | incident_id=%s | chars=%d",
                incident_id,
                len(summary_md),
            )

        except Exception as exc:
            logger.error(
                "ReportingAgent LLM call failed | incident_id=%s | error=%s — using fallback",
                incident_id,
                exc,
            )
            fixture = get_demo_fixture(ioc)
            if fixture and "report" in fixture and "summary_md" in fixture["report"]:
                summary_md = fixture["report"]["summary_md"].replace("{INCIDENT_ID}", incident_id)
                model_used = "demo-fixture-fallback"
            else:
                summary_md = _fallback_report(
                    incident_id=incident_id,
                    triage_json=triage_json,
                    intel_json=intel_json,
                    risk_score=risk_score,
                    risk_assessment=risk_assessment,
                    deception_path=deception_path,
                )
                model_used = "fallback"

        return {
            "incident_id":  incident_id,
            "summary_md":   summary_md,
            "generated_at": generated_at,
            "model":        model_used,
        }


# ---------------------------------------------------------------------------
# Explainability Engine ("Ask the SOC" Q&A)
# ---------------------------------------------------------------------------

_EXPLAIN_SYSTEM_PROMPT = """\
You are CHIMERA SOC. Answer the user's question using ONLY the provided incident context. Do not invent external facts. Be concise.
"""


def _build_explain_context(
    incident_id: str,
    incident_data: Dict[str, Any],
    fixture: Dict[str, Any],
) -> str:
    source_ip = incident_data.get("source_ip", "185.220.101.42")
    title = incident_data.get("title", "Security Incident")
    severity = incident_data.get("severity", "CRITICAL")
    risk_score = float(incident_data.get("risk_score", 0.842))
    confidence = float(incident_data.get("confidence", 0.94))
    mitre_tech = incident_data.get("mitre_technique", "T1190 – Exploit Public-Facing Application")
    cert_cat = incident_data.get("cert_in_category", "Unauthorized access to IT systems or data")
    decoy_path = incident_data.get("decoy_path", "/decoy/db-admin")
    status = incident_data.get("status", "PENDING_APPROVAL")
    endpoint = incident_data.get("endpoint") or fixture.get("endpoint", "/api/admin/config")

    rep = fixture.get("reputation", {})
    vt_score = rep.get("vt_score", "48/72 Engines Flagged")
    abuse_score = rep.get("abuse_score", "96% Abuse Confidence")
    tavily_data = fixture.get("tavily", {})
    tavily_ans = tavily_data.get("answer", "")

    chatter_list = fixture.get("chatter", [])
    chatter_text = "\n".join(
        f"- [{c.get('agent', 'AGENT')}] {c.get('reasoning', '')}" for c in chatter_list
    ) if chatter_list else f"- [TRIAGE] Anomaly detected on {endpoint}.\n- [INTEL] Enriched via Tavily & VirusTotal.\n- [RISK] Calculated risk {risk_score:.3f}.\n- [DECEPTION] Routed to {decoy_path}."

    return f"""\
- Incident ID: {incident_id}
- Target Source IP: {source_ip}
- Target Endpoint: {endpoint}
- Incident Title: {title}
- Severity: {severity}
- Incident Status: {status}
- Composite Risk Score: {risk_score:.3f} (Autonomy Cutoff: 0.40)
- Threat Confidence: {confidence * 100:.0f}%
- MITRE ATT&CK: {mitre_tech}
- CERT-In Category: {cert_cat}
- Deception Decoy: {decoy_path}
- VirusTotal Reputation: {vt_score}
- AbuseIPDB Reputation: {abuse_score}
- Threat Intel Summary: {tavily_ans or 'Active scanning and exploit node targeting web applications.'}
- Agent Reasoning Trace:
{chatter_text}
- Graph Topology: {source_ip} (Attacker) ➔ WAF ➔ {decoy_path} (Honeypot)
"""


def _generate_deterministic_explanation(
    incident_id: str,
    incident_data: Dict[str, Any],
    fixture: Dict[str, Any],
    query: str,
) -> str:
    source_ip = incident_data.get("source_ip", "185.220.101.42")
    title = incident_data.get("title", "Security Incident")
    severity = incident_data.get("severity", "CRITICAL")
    risk_score = float(incident_data.get("risk_score", 0.842))
    confidence = float(incident_data.get("confidence", 0.94))
    mitre_tech = incident_data.get("mitre_technique", "T1190 – Exploit Public-Facing Application")
    cert_cat = incident_data.get("cert_in_category", "Unauthorized access to IT systems or data")
    decoy_path = incident_data.get("decoy_path", "/decoy/db-admin")
    endpoint = incident_data.get("endpoint") or fixture.get("endpoint", "/api/admin/config")

    rep = fixture.get("reputation", {})
    vt_score = rep.get("vt_score", "48/72 Engines Flagged")
    abuse_score = rep.get("abuse_score", "96% Abuse Confidence")
    tavily_data = fixture.get("tavily", {})
    tavily_ans = tavily_data.get("answer", "")

    q_lower = query.lower()

    if any(w in q_lower for w in ["critical", "severity", "score", "risk", "classify", "classified", "classification"]):
        return (
            f"This incident was classified as {severity} with a Risk Score of {risk_score:.3f} and {confidence * 100:.0f}% "
            f"detection confidence because the attacker directly targeted {endpoint} using {mitre_tech}. "
            f"Combined with malicious IOC reputation ({vt_score}), the blast radius model evaluated potential impact "
            f"to production database infrastructure, categorizing it under CERT-In guidelines as '{cert_cat}'."
        )
    elif any(w in q_lower for w in ["block", "contain", "isolated", "isolation", "quarantine", "containment", "why did we", "why block"]):
        return (
            f"IP {source_ip} was targeted for containment because TriageAgent identified high-entropy exploitation "
            f"on {endpoint} matching MITRE {mitre_tech} with {confidence * 100:.0f}% confidence. ThreatIntelAgent verified "
            f"hostile reputation ({vt_score} on VirusTotal, {abuse_score} on AbuseIPDB). RiskEngine calculated a composite "
            f"risk score of {risk_score:.3f} (exceeding the 0.40 autonomy cutoff), justifying perimeter firewall containment "
            f"to protect core assets while DeceptionAgent sinkholed active probes into {decoy_path}."
        )

    elif any(w in q_lower for w in ["decoy", "honeypot", "deception", "trap", "sinkhole"]):
        return (
            f"DeceptionAgent trapped traffic from {source_ip} by transparently rerouting the attacker to the decoy honeypot "
            f"'{decoy_path}'. This high-interaction decoy emulates genuine administrative responses, capturing attacker "
            f"tooling and SQL payloads without exposing production services."
        )
    elif any(w in q_lower for w in ["intel", "tavily", "virustotal", "abuse", "reputation", "ioc"]):
        intel_desc = tavily_ans if tavily_ans else "Known hostile exploit origin conducting automated scanning campaigns."
        return (
            f"Threat Intelligence enrichment via Swytchcode and Tavily identified {source_ip} with {vt_score} on VirusTotal "
            f"and {abuse_score} on AbuseIPDB. {intel_desc}"
        )
    elif any(w in q_lower for w in ["mitre", "technique", "tactic"]):
        return (
            f"TriageAgent mapped this incident to MITRE technique {mitre_tech}. The heuristic payload analysis matched "
            f"exploit probes against {endpoint}, indicating unauthorized initial access attempts."
        )
    elif any(w in q_lower for w in ["cert", "compliance", "6-hour", "report"]):
        return (
            f"Under CERT-In cyber security guidelines, this incident is categorized as '{cert_cat}'. Mandatory statutory "
            f"notification within 6 hours of detection is tracked by the active compliance clock."
        )
    else:
        return (
            f"For incident {incident_id} ({source_ip}), CHIMERA detected {title} (MITRE {mitre_tech}) with a risk score of "
            f"{risk_score:.3f} ({confidence * 100:.0f}% confidence). Threat intelligence confirmed hostile reputation ({vt_score}), "
            f"and the attacker was routed to {decoy_path} while perimeter containment rules were prepared."
        )


async def explain_incident(
    incident_id: str,
    query: str,
    incident_data: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Explainability Engine for Incident Dossier Q&A ("Ask the SOC").
    Strictly answers user questions using ONLY the provided incident context.
    """
    import os

    if incident_data is None:
        try:
            from backend.main import INCIDENTS
            incident_data = next((inc for inc in INCIDENTS if inc.get("id") == incident_id), None)
        except Exception:
            incident_data = None

    if incident_data is None:
        incident_data = {
            "id": incident_id,
            "title": "SQL Injection on Public Endpoint (/api/admin/config)",
            "source_ip": "185.220.101.42",
            "severity": "CRITICAL",
            "cert_in_category": "Unauthorized access to IT systems or data",
            "risk_score": 0.842,
            "confidence": 0.94,
            "status": "PENDING_APPROVAL",
            "mitre_technique": "T1190 – Exploit Public-Facing Application",
            "decoy_path": "/decoy/db-admin",
            "created_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S IST"),
        }

    source_ip = incident_data.get("source_ip", "185.220.101.42")
    fixture = get_demo_fixture(source_ip) or {}

    # Check DEMO_MODE
    if is_demo_mode():
        await simulate_agent_latency(200, 350)
        answer = _generate_deterministic_explanation(incident_id, incident_data, fixture, query)
        return {
            "status": "success",
            "incident_id": incident_id,
            "query": query,
            "answer": answer,
            "model": "chimera-explain-deterministic-rehearsal",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    # Live LLM inference path
    context_bundle = _build_explain_context(incident_id, incident_data, fixture)
    groq_api_key = os.environ.get("GROQ_API_KEY") or getattr(settings, "GROQ_API_KEY", None)

    if AsyncGroq is not None and groq_api_key:
        try:
            groq_client = AsyncGroq(api_key=groq_api_key)
            chat = await groq_client.chat.completions.create(
                model=_GROQ_MODEL,
                messages=[
                    {"role": "system", "content": _EXPLAIN_SYSTEM_PROMPT},
                    {"role": "user", "content": f"[INCIDENT CONTEXT]\n{context_bundle}\n\n[USER QUESTION]\n{query}"},
                ],
                temperature=0.2,
                max_tokens=600,
            )
            raw_ans = chat.choices[0].message.content or ""
            answer = _strip_fences(raw_ans)
            model_used = _GROQ_MODEL
        except Exception as exc:
            logger.warning(f"[Explain] Groq call failed ({exc}), falling back to deterministic explanation")
            answer = _generate_deterministic_explanation(incident_id, incident_data, fixture, query)
            model_used = "chimera-explain-fallback"
    else:
        answer = _generate_deterministic_explanation(incident_id, incident_data, fixture, query)
        model_used = "chimera-explain-deterministic"

    return {
        "status": "success",
        "incident_id": incident_id,
        "query": query,
        "answer": answer,
        "model": model_used,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }

