"""
backend/agents/reporting_agent.py

ReportingAgent — generates a concise Markdown forensic report from all
gathered pipeline data using an LLM.

Input bundle (passed as keyword arguments or a dict):
    triage_json    : dict from TriageAgent.classify()
    intel_json     : dict from ThreatIntelAgent.enrich()
    risk_score     : float from RiskEngine.calculate_risk()
    risk_assessment: dict from RiskEngine.evaluate_action()
    graph_edges    : list[dict] — graph_edges records from DeceptionAgent
    incident_id    : str (optional — used in the report header)
    deception_path : str (optional — decoy path from DeceptionAgent)

Output:
    {
        "incident_id":  str,
        "summary_md":   str,   ← full Markdown forensic report
        "generated_at": str,   ← ISO-8601 UTC timestamp
        "model":        str,
    }
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timezone
from typing import Any

from groq import AsyncGroq

from backend.config import settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# LLM configuration
# ---------------------------------------------------------------------------

_GROQ_MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = """\
You are CHIMERA Forensics — an elite SOC reporting analyst AI embedded in
an autonomous Security Operations Centre.

You will be given a structured JSON bundle containing the full pipeline output
for a single security incident. Your task is to synthesise this data into a
concise, professional Markdown forensic report.

## Report Structure (use these exact headings):

# 🛡️ CHIMERA Incident Report — {INCIDENT_ID}

## Executive Summary
*2–3 sentence non-technical summary for leadership.*

## Threat Classification
| Field             | Value |
|-------------------|-------|
| Severity          | ...   |
| MITRE Tactic      | ...   |
| MITRE Technique   | ...   |
| Confidence Score  | ...   |
| Risk Score        | ...   |
| Risk Band         | ...   |

## Threat Intelligence
*Summarise the IOC reputation and Tavily web findings in 3–5 sentences.*

## Timeline & Attack Chain
*Bullet list of the key events/steps inferred from the data.*

## Deception Layer
*State which decoy endpoint the attacker was redirected to and why.*

## Recommended Actions
*Bullet list of concrete, prioritised remediation steps.*
Prefix critical items with ⚠️.

## Graph Topology
*Briefly describe the recorded graph edges (attacker → decoy).*

---
*Generated by CHIMERA AutoSOC at {TIMESTAMP} UTC*

Rules:
- Use only the data provided — do NOT invent facts.
- Keep the report under 600 words.
- All headings must use exactly the format shown.
- Use Markdown tables where structure helps readability.
- Highlight critical items with ⚠️ or **bold**.
- Respond with ONLY the Markdown report — no preamble, no JSON, no code fences.
"""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_bundle_summary(
    triage_json: dict[str, Any],
    intel_json: dict[str, Any],
    risk_score: float,
    risk_assessment: dict[str, Any],
    graph_edges: list[dict[str, Any]],
    incident_id: str,
    deception_path: str,
) -> str:
    """Serialise the full pipeline bundle into a compact prompt payload."""
    bundle = {
        "incident_id": incident_id,
        "triage": triage_json,
        "intel": intel_json,
        "risk_score": round(risk_score, 4),
        "risk_assessment": risk_assessment,
        "graph_edges": graph_edges,
        "deception_path": deception_path,
    }
    return json.dumps(bundle, indent=2, default=str)


def _inject_prompt_vars(system: str, incident_id: str) -> str:
    """Fill template variables in the system prompt."""
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    return (
        system
        .replace("{INCIDENT_ID}", incident_id)
        .replace("{TIMESTAMP}", now_utc)
    )


def _strip_fences(text: str) -> str:
    """Remove accidental markdown code fences the LLM may add."""
    text = re.sub(r"^```(?:markdown)?\s*\n?", "", text.strip(), flags=re.IGNORECASE)
    text = re.sub(r"\n?```\s*$", "", text.strip(), flags=re.IGNORECASE)
    return text.strip()


def _fallback_report(
    incident_id: str,
    triage_json: dict[str, Any],
    intel_json: dict[str, Any],
    risk_score: float,
    risk_assessment: dict[str, Any],
    deception_path: str,
) -> str:
    """Rule-based Markdown report used when the LLM is unavailable."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    severity   = triage_json.get("severity", "UNKNOWN")
    tactic     = triage_json.get("mitre_tactic", "Unknown")
    technique  = triage_json.get("mitre_technique", "Unknown")
    reasoning  = triage_json.get("reasoning", "")
    ioc        = intel_json.get("ioc", "N/A")
    confidence = intel_json.get("confidence_score", 0.0)
    context    = intel_json.get("threat_context", "")
    action     = risk_assessment.get("action", "unknown")
    risk_label = risk_assessment.get("risk_label", "UNKNOWN")
    requires_h = risk_assessment.get("requires_human", False)

    return f"""# 🛡️ CHIMERA Incident Report — {incident_id}

## Executive Summary
A **{severity}** severity event was detected and automatically triaged by the CHIMERA \
multi-agent pipeline. The attacker IOC `{ioc}` has a threat confidence of **{confidence:.0%}** \
and a composite risk score of **{risk_score:.4f}** ({risk_label}). \
{"⚠️ Human analyst review is required." if requires_h else "Automated containment has been initiated."}

## Threat Classification
| Field             | Value                  |
|-------------------|------------------------|
| Severity          | {severity}             |
| MITRE Tactic      | {tactic}               |
| MITRE Technique   | {technique}            |
| Confidence Score  | {confidence:.4f}       |
| Risk Score        | {risk_score:.4f}       |
| Risk Band         | {risk_label}           |

## Threat Intelligence
{context if context else "No threat context available."}

## Timeline & Attack Chain
- IOC `{ioc}` flagged by XGBoost EdgeFilter
- TriageAgent classified as **{severity}** — {reasoning}
- ThreatIntelAgent enrichment completed (confidence: {confidence:.2%})
- Risk score computed: {risk_score:.4f} → action: **{action}**
- Attacker redirected to decoy endpoint: `{deception_path}`

## Deception Layer
The attacker was redirected to `{deception_path}` based on the detected \
MITRE technique **{technique}**, directing activity away from production systems.

## Recommended Actions
{"⚠️ **Escalate to Tier-2 analyst immediately.**" if requires_h else "- ✅ Automated containment initiated."}
- Verify `{ioc}` is blocked at the perimeter firewall.
- Cross-reference with SIEM for historical activity from this IOC.
- Review graph topology for lateral movement indicators.

## Graph Topology
The graph edge `ip:{ioc}` → `decoy:{deception_path}` (type: `redirected_to`) \
has been recorded in the graph database.

---
*Generated by CHIMERA AutoSOC (fallback mode) at {now} UTC*
"""


# ---------------------------------------------------------------------------
# Public agent class
# ---------------------------------------------------------------------------

class ReportingAgent:
    """
    Generates a Markdown forensic report from the full CHIMERA pipeline output.

    Usage::

        agent = ReportingAgent()
        result = await agent.generate_report(
            incident_id   = "INC-2024-0042",
            triage_json   = triage_result,
            intel_json    = intel_result,
            risk_score    = 0.6120,
            risk_assessment = risk_decision,
            graph_edges   = [edge_record],
            deception_path = "/decoy/db-admin",
        )
        print(result["summary_md"])
    """

    async def generate_report(
        self,
        incident_id: str,
        triage_json: dict[str, Any],
        intel_json: dict[str, Any],
        risk_score: float,
        risk_assessment: dict[str, Any],
        graph_edges: list[dict[str, Any]] | None = None,
        deception_path: str = "",
    ) -> dict[str, Any]:
        """
        Generate a Markdown forensic report using an LLM.

        Parameters
        ----------
        incident_id:
            Unique incident identifier string (e.g. ``"INC-2024-0042"``).
        triage_json:
            Output dict from ``TriageAgent.classify()``.
        intel_json:
            Output dict from ``ThreatIntelAgent.enrich()``.
        risk_score:
            Float from ``RiskEngine.calculate_risk()``.
        risk_assessment:
            Output dict from ``RiskEngine.evaluate_action()``.
        graph_edges:
            List of ``graph_edges`` row dicts from ``DeceptionAgent``
            (may be empty or ``None``).
        deception_path:
            The decoy path the attacker was routed to (e.g. ``"/decoy/db-admin"``).

        Returns
        -------
        dict with keys:
            - ``incident_id``  – echoed incident ID
            - ``summary_md``   – full Markdown forensic report
            - ``generated_at`` – ISO-8601 UTC timestamp
            - ``model``        – LLM model used (or ``"fallback"`` if unavailable)
        """
        graph_edges = graph_edges or []
        generated_at = datetime.now(timezone.utc).isoformat()

        logger.info(
            "ReportingAgent.generate_report | incident_id=%s | risk=%.4f",
            incident_id,
            risk_score,
        )

        # Build the user payload
        bundle_text = _build_bundle_summary(
            triage_json=triage_json,
            intel_json=intel_json,
            risk_score=risk_score,
            risk_assessment=risk_assessment,
            graph_edges=graph_edges,
            incident_id=incident_id,
            deception_path=deception_path,
        )

        # Inject template variables into system prompt
        system = _inject_prompt_vars(_SYSTEM_PROMPT, incident_id)

        try:
            groq_client = AsyncGroq(api_key=None)
            chat = await groq_client.chat.completions.create(
                model=_GROQ_MODEL,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user",   "content": bundle_text},
                ],
                temperature=0.3,    # slight creativity for readable prose
                max_tokens=1500,
                # Markdown output — do NOT use json_object mode here
            )
            raw_md = chat.choices[0].message.content or ""
            summary_md = _strip_fences(raw_md)
            model_used = _GROQ_MODEL

            logger.info(
                "ReportingAgent report generated | incident_id=%s | chars=%d",
                incident_id,
                len(summary_md),
            )

        except Exception as exc:
            logger.error(
                "ReportingAgent LLM call failed | incident_id=%s | error=%s — using fallback",
                incident_id,
                exc,
            )
            summary_md = _fallback_report(
                incident_id=incident_id,
                triage_json=triage_json,
                intel_json=intel_json,
                risk_score=risk_score,
                risk_assessment=risk_assessment,
                deception_path=deception_path,
            )
            model_used = "fallback"

        return {
            "incident_id":  incident_id,
            "summary_md":   summary_md,
            "generated_at": generated_at,
            "model":        model_used,
        }
